# Nicotine Default Configuration

# Application Settings
app:
  name: "Nicotine AI Hallucination Detection Service"
  version: "1.0.0"
  debug: false
  log_level: "INFO"

# API Settings
api:
  host: "0.0.0.0"
  port: 8000
  docs_url: "/docs"
  redoc_url: "/redoc"
  cors:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]
    allow_credentials: true

# OpenAI Settings
openai:
  api_key: null # Set via environment variable OPENAI_API_KEY
  default_model: "gpt-4"
  default_temperature: 0.7
  default_max_tokens: 1000
  timeout: 30
  max_retries: 3

# Hallucination Detection Settings
hallucination_detection:
  confidence_threshold: 0.8
  delusion_threshold: 50.0 # percentage
  enable_caching: false
  cache_ttl: 3600 # seconds

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null # Set to file path to enable file logging
  max_file_size: "10MB"
  backup_count: 5

# Health Check Settings
health:
  enabled: true
  timeout: 5
  dependencies: []

# Metrics and Monitoring
metrics:
  enabled: false
  endpoint: "/metrics"
  include_request_metrics: true
  include_response_metrics: true
